name: CI/CD Backend

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure container registry
        uses: docker/login-action@v3
        with:
          registry: fincicd.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS_USERNAME }}
          password: ${{ secrets.AZURE_CREDENTIALS_PASSWORD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to github registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: fincicd.azurecr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./api/Dockerfile
     


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker
    # : github.ref == 'refs/heads/master'

  #   steps:
  #     - name: Log in to Azure
  #       uses: azure/login@v1
  #       with:
  #         creds: {{ secrets.AZURE_CREDENTIALS }}

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: {{ secrets.AZURE_WEB_APP_NAME }}
  #         images: |
  #           {{ secrets.AZURE_CONTAINER_REGISTRY }}/dotnet-api:{{ github.sha }}

          



